// pedir para o usuario digitar um numero 
var n1 = prompt('digite um numero');
//converter  em numero  inteiro 
n1 = parseInt(n1);

//pedir para o usuario  digitar outro numero 
var n2 = prompt('digite outro numero');
//converter em numero inteiro 
n2 = parseInt(n2);

//mostrar a subtrçao concatenando com  o texto "a subtração é:..."
alert("A subtração é:"+ (n1 - n2));

//mostrar a soma concatenando com o texto  "a soma é: ..."
alert("A soma é:"+ (n1 + n2));

//mostrar a subtrçao concatenando com  o texto "a divisao é:..."
alert("A subtração é:"+ (n1 / n2));

//mostrar a multiplicaçao concatenando com o texto "a multiplicaçao é:..."
alert("A multiplicação é:"+ (n1 * n2));
alert("A multiplicação é:"+ (n1 * n2));
